name: GitHub Terraform
on: [push]
env:
    ARM_CLIENT_ID: "${{secrets.AZURE_CLIENT_ID}}"
    ARM_SUBSCRIPTION_ID: "${{secrets.AZURE_SUBSCRIPTION_ID}}"
    ARM_TENANT_ID: "${{secrets.AZURE_TENANT_ID}}"
    ARM_SECRET_CLIENT: "${{secrets.AZURE_SECRET_CLIENT}}"
jobs:
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3