name: GitHub Terraform
on: [push]
env:
    ARM_CLIENT_ID: "${{secrets.AZURE_CLIENT_ID}}"
    ARM_SUBSCRIPTION_ID: "${{secrets.AZURE_SUBSCRIPTION_ID}}"
    ARM_TENANT_ID: "${{secrets.AZURE_TENANT_ID}}"
    ARM_SECRET_CLIENT: "${{secrets.AZURE_SECRET_CLIENT}}"
jobs:
    terraform-plan:
        name: "Terraform plan"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}
            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}
            - name: Terraform Init
              run: terraform init -reconfigure -input=false -backend-config="storage_account_name=mytfstatesahca" -backend-config="container_name=tfstate" -backend-config="access_key=${{secrets.AZURE_STORAGE_ACCESS_KEY}}" -backend-config="key=dev/terraform.tfstate"
            - id: plan
              name: Terraform Plan
              run: terraform plan -no-color -var appId=$ARM_CLIENT_ID -var password=$ARM_SECRET_CLIENT
            - id: apply
              name: Terraform Apply
              run: terraform apply -auto-approve