name: Terraform Destroy
on:
    workflow_dispatch: 

jobs:
    destroy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}
            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}
            - name: Terraform init
              run: terraform init -backend-config="storage_account_name=mytfstatesahca" -backend-config="container_name=tfstate" -backend-config="access_key=${{secrets.AZURE_STORAGE_ACCESS_KEY}}" -backend-config="key=dev/terraform.tfstate"
            - name: Terraform destroy
              run: terraform destroy -auto-approve -var appId=$ARM_CLIENT_ID -var password=$ARM_SECRET_CLIENT             